### ISSUE TITLE
boiled_egg_graphical() returns duplicate plots and fails upon re-running

### ISSUE THREAD

**Issue by fernan** [ikmckenz/adme-pred-py#15]
Hi! 

I am testing and getting familiar with adme-pred.py (great work BTW!), and I found this issue when running boiled_egg_graphical(). 

```
from adme_pred import ADME

# aspirin
mol = ADME("CC(=O)OC1=CC=CC=C1C(=O)O")

# works but generates identical duplicate plots
mol.boiled_egg_graphical()

``` 
![image](https://user-images.githubusercontent.com/175475/227665535-8941c93b-52b2-4a2b-a03e-a3d5c49b9cbc.png)

Also, not sure if this is related or needs to be a separate issue, but when running the same code cell again, it produces an empty plot and gives an error which suggests that the way `adme-pred-py`  generates the matplotlib plot breaks upon re-running. 

```
# fails with an error
mol.boiled_egg_graphical()
```

**This is the error:**

```
[/usr/local/lib/python3.9/dist-packages/adme_pred/adme_pred.py](https://localhost:8080/#) in boiled_egg_graphical(self)
    329         white.set_clip_box(axis.bbox)
    330         white.set_facecolor("white")
--> 331         axis.add_artist(white)
    332 
    333         yolk.set_clip_box(axis.bbox)

[/usr/local/lib/python3.9/dist-packages/matplotlib/axes/_base.py](https://localhost:8080/#) in add_artist(self, a)
   2217         ``ax.transData``.
   2218         """
-> 2219         a.axes = self
   2220         self._children.append(a)
   2221         a._remove_method = self._children.remove

[/usr/local/lib/python3.9/dist-packages/matplotlib/artist.py](https://localhost:8080/#) in axes(self, new_axes)
    302         if (new_axes is not None and self._axes is not None
    303                 and new_axes != self._axes):
--> 304             raise ValueError("Can not reset the axes.  You are probably "
    305                              "trying to re-use an artist in more than one "
    306                              "Axes which is not supported")

ValueError: Can not reset the axes.  You are probably trying to re-use an artist in more than one Axes which is not supported
```

![image](https://user-images.githubusercontent.com/175475/227667048-4af0dcbe-43a5-4814-bb69-66abded3f9ab.png)

And not sure if this gives you a clue, but when running twice in the same cell, now one plot is OK, the other is empty (still you get the same error about reusing/resetting the matplotlib axes). 

```
mol.boiled_egg_graphical()
mol.boiled_egg_graphical()
```

![image](https://user-images.githubusercontent.com/175475/227667635-19cb5e60-0040-4041-a0d3-f1f6dc17d1c1.png)

**Environment:**
This is on a Google Colab notebook running python v3.9.16, with a fresh installation of rdkit-2022.9.5 (from pypi), and adme-pred.py 0.0.1 from github. 

```
!pip install git+https://github.com/ikmckenz/adme-pred-py.git
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/ikmckenz/adme-pred-py.git
  Cloning https://github.com/ikmckenz/adme-pred-py.git to /tmp/pip-req-build-s2b5gnov
  Running command git clone --filter=blob:none --quiet https://github.com/ikmckenz/adme-pred-py.git /tmp/pip-req-build-s2b5gnov
  Resolved https://github.com/ikmckenz/adme-pred-py.git to commit 1dcd1f1c94b8c8ee45ed6bf91994194b57cc4215
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: adme-pred
  Building wheel for adme-pred (setup.py) ... done
  Created wheel for adme-pred: filename=adme_pred-0.0.1-py3-none-any.whl size=18553 sha256=6686f1d7969a0abbffb3b7da252f3d934787936e8cc59943e65f4bcc71aafc37
  Stored in directory: /tmp/pip-ephem-wheel-cache-ri0kbmth/wheels/45/42/a4/41f1aafe9dbd4f1f03ef164df2610e2939edbb5e8a2b289a19
Successfully built adme-pred
Installing collected packages: adme-pred
Successfully installed adme-pred-0.0.1

!pip install rdkit
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting rdkit
  Downloading rdkit-2022.9.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 37.3 MB/s eta 0:00:00
Requirement already satisfied: Pillow in /usr/local/lib/python3.9/dist-packages (from rdkit) (8.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from rdkit) (1.22.4)
Installing collected packages: rdkit
Successfully installed rdkit-2022.9.5
```

**Comment by ikmckenz** [comment]
Thank you for the thorough bug report! Originally I hadn't used this code in a Jupyter Notebook so this is valuable feedback. 

1. The `boiled_egg_graphical()` function generates the plot, and also returns it from the function. Jupyter Notebook is displaying it twice: Once when it's built, and secondly when it is returned. I think I probably want to keep returning the plot in case it needs to be further edited or controlled programmatically, so to avoid the dual printing I would assign the output of the function to a variable. `myplot = mol.boiled_egg_graphical()` fixes this issue. I have added type annotations to the function to show this behaviour.
2. Multiple runs of the function no longer fail. This was caused by initiating the Ellipses and reusing them on matplotlit artists, they are now deep copied and the issue is resolved. 

Please run `conda update -c ikmckenz adme-pred-py` and see if the new code fixes your issues!
